### PR TITLE
Fixed packaging issues

### PR DESCRIPTION
**Pull request by sprat**
Fixed packaging issues as discussed in https://github.com/joelrich/citojs/issues/24
- added a UMD boilerplate so that the library is compatible with AMD, CommonJS and browser environments. It works in browserify builds now.
- added missing metadata in package.json

### CODE REVIEW

**Comment by sprat** [comment]
Forgot to add some explanations:
1. maybe we should change the package name to cito. As it is now, we must require('citojs')
2. I've removed the "window" and "undefined" parameters due to the UMD wrapper. I don't think it's really problematic, but please comment if you think it is!

**Comment by joelrich** [comment]
@sprat thanks a lot, I have merged the commit and renamed the project from citojs to cito. In case you are interested, it would be great if you could add some tests for the different module types as well.

**Comment by sprat** [comment]
Thanks for merging and renaming!

About the module tests: I generally add tests for everything I do, but I don't see how this can be tested simply and automatically. Plus, it's a standard boilerplate, we should not expect many problems with that. So I don't think it's worth testing.

**Comment by barneycarroll** [comment]
Add `npm install` as the npm `test` script? ;)

**Comment by sprat** [comment]
I'm not sure I understand what you are asking. Do you mean adding an "install" script? Doing what? A build? Is this script called when we install the library as a dependency of another project?

**Comment by barneycarroll** [comment]
Sorry @sprat that was a silly joke. The problem is that within the context of a package it's impossible to validate it's ability to work as a package in external contexts. The reduced test case irony is that you need to `npm install` before you can run `npm test`, therefore it is demonstrable that it is impossible to validate the ability of a package to install without installing it.

**Comment by barneycarroll** [comment]
BTW, awesome work! Thanks!

**Pull request merged**
